# Generated by Django 3.0.4 on 2020-03-11 17:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module_code', models.CharField(max_length=4, unique=True)),
                ('module_name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ModuleInstance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveSmallIntegerField()),
                ('semester', models.PositiveSmallIntegerField()),
                ('module_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cwk1Application.Module')),
            ],
        ),
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prof_code', models.CharField(max_length=4, unique=True)),
                ('prof_name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField()),
                ('module_instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cwk1Application.ModuleInstance')),
                ('professor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cwk1Application.Professor')),
            ],
        ),
        migrations.AddField(
            model_name='moduleinstance',
            name='taught_by',
            field=models.ManyToManyField(to='cwk1Application.Professor'),
        ),
    ]
